name: Tindel
favicon: null
layout_spectrum: 0.822295289253816
typography_spectrum: 0.5723979494068772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4696221365593374
  lightness: 0.521303862798959
  saturation: 0.8690347014926374
  rhythmicContrast: 0.00022249692119657993
purpose: []
