name: Tindel
favicon: null
layout_spectrum: 0.75073
typography_spectrum: 0.62536
title: ACreative Life in the American South
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#12121c'
    - '#737277'
    - '#9ab4cf'
    - '#911632'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
