name: Tindel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65045
title: The Art of John Tindel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#dedede'
    - '#aeaeae'
    - '#6c6c6c'
  brandStrength: 0
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
