name: Tindel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65045
title: The Art of John Tindel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060203'
    - '#f7e3c8'
    - '#956942'
    - '#c2a981'
    - '#fdd909'
  brandStrength: 0.0625
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
