name: Tindel
favicon: null
layout_spectrum: 0.78153
typography_spectrum: 0.91389
title: The Art of John Tindel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#dedede'
    - '#aeaeae'
    - '#6c6c6c'
  brandStrength: 0.3125
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
