typography_spectrum: 0.62536
color:
  brandColors:
    - '#ffffff'
    - '#12121c'
    - '#737277'
    - '#9ab4cf'
    - '#911632'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75073
analytics:
  google: null
  facebook: null
  twitter: null
name: Tindel
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Imagination Bureau LLC
purpose: []
