name: Tindel
favicon: null
layout_spectrum: 0
typography_spectrum: 0.63455
title: The Art of John Tindel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5e4b7'
    - '#000000'
    - '#0ffdfa'
    - '#5d577b'
    - '#065414'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
