name: Tindel
favicon: null
layout_spectrum: 0.50596
typography_spectrum: 0.65045
title: The Art of John Tindel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#fee7fd'
    - '#463231'
    - '#7b5f63'
    - '#fcaaa1'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
