name: Tindel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.91389
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00ffff'
    - '#231f20'
    - '#157374'
    - '#0ea2a2'
    - '#01c6c6'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
