name: Tindel
favicon: null
layout_spectrum: 0.2693
typography_spectrum: 0.19206
title: The Art of John Tindel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#12121c'
    - '#737277'
    - '#9ab4cf'
    - '#911632'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
